server {
    listen 80;
    server_name project.cop4331.cc;

    root /usr/share/nginx/html;
    index index.html;

    # This is critical for React Router / client-side routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}