services:
  frontend:
    image: poosdproject/frontend
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile
    ports:
      - 80:80
      - 443:443

  backend:
    image: poosdproject/backend
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    ports:
      - 3000:3000
    env_file:
    - path: ./backend/.env
      required: true
