@startuml
top to bottom direction
skinparam linetype ortho

actor "Teacher (User)" as User

rectangle "POOSD Final Project" {

    package "Authentication" {
        (Create Account) as Register
        (Log In) as Login
        (Recover Password) as ForgotPassword

        Login .> ForgotPassword : <<extend>>\n
    }

    User --> Register
    User --> Login


    package "Account" {
        (Manage Account) as ManageAcc
        (View Account Info) as ViewAcc
        (Update Account Info) as UpdateAcc
        
        ManageAcc --> ViewAcc : <<include>>
        ManageAcc --> UpdateAcc : <<include>>
    }

    User --> ManageAcc


    package "Dashboard" {
        (View Dashboard) as Dashboardd
    }

    User --> Dashboard

    package "Topics" {
        (Manage Topics) as MT
        (Create Topic) as CT
        (Delete Topic) as DT
        (Update Topic) as UT
        (View Topics) as VT

        MT --> UT : <<include>>
        MT --> CT : <<include>>
        MT --> DT : <<include>>
        MT --> VT : <<include>>
    }

    User --> MT


    package "Questions" {
        (Manage Questions) as MQ
        (Create Question) as CQ
        (Delete Question) as DQ
        (View Questions) as VQ
        (Get Question Details) as GQ
        (Check Answers) as CA

        MQ --> CQ : <<include>>
        MQ --> DQ : <<include>>
        MQ --> VQ : <<include>>

        VQ --> GQ : <<include>>
        CA --> GQ : <<include>>
    }

    User --> MQ
    User --> CA

}

@enduml
