@startuml
top to bottom direction
skinparam linetype ortho

actor "Teacher (User)" as User

rectangle "POOSD Final Project" {

    ' ACCOUNT
    (Create Account) as Register
    (Log In) as Login
    (Recover Password) as ForgotPassword

    (Manage Account) as Account
    (View Account Info) as ViewAcc
    (Update Account Info) as UpdateAcc

    User --> Register
    User --> Login

    Login .> ForgotPassword : <<extend>>

    User --> Account
    Account --> ViewAcc : <<include>>


    ' DASHBOARD
    (View Dashboard) as Dashboard
    User --> Dashboard


    ' TOPICS
    (Manage Topics) as MT
    (Create Topic) as CT
    (Delete Topic) as DT
    (Update Topic) as UT
    (View Topics) as VT

    User --> MT

    MT --> CT : <<include>>
    MT --> DT : <<include>>
    MT --> UT : <<include>>
    MT --> VT : <<include>>


    ' QUESTIONS
    (Manage Questions) as MQ
    (Create Question) as CQ
    (Delete Question) as DQ
    (View Questions) as VQ
    (Get Question Details) as GQ
    (Check Answers) as CA

    User --> MQ
    User --> CA

    MQ --> CQ : <<include>>
    MQ --> DQ : <<include>>
    MQ --> VQ : <<include>>

    VQ --> GQ : <<include>>
    CA --> GQ : <<include>>

}

@enduml
