# .github/workflows/ci.yml
name: Tests

on:
  push:
    branches: [mobile]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setting up environment variables
        run: |
            cat > backend/.env << EOF
            DATABASE_URL=mongodb://root:testpassword@mongodb:27017
            JWT_SECRET=todo
            EMAIL_SENDER=${{secrets.EMAIL_SENDER}}
            SES_SMTP_HOST=${{secrets.SES_SMTP_HOST}}
            IAM_USER_NAME=${{secrets.IAM_USER_NAME}}
            SES_SMTP_PASSWORD=${{secrets.SES_SMTP_PASSWORD}}
            DOMAIN=${{secrets.DOMAIN}}
            
      - name: Setting up services
        run: docker compose up --build -d mongodb backend

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
    
      - name: Dependencies Backend
        run: npm --prefix ./backend install ./backend
      - name: Builiding backend
        run: npm --prefix ./backend run build
      - name: Dependencies frontend (For tests)
        run: npm --prefix ./frontend install ./frontend
      - name: Building frontend
        run: npm --prefix ./frontend run build
      - name: Install dependencies
        run: npm --prefix ./tests install ./tests
      - name: Run tests
        run: npm --prefix ./tests test 
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter pub get
        run: flutter pub get
        working-directory: mobile
      - name: Run widget tests
        run: flutter test test/widget_test.dart
        working-directory: mobile
      - name: Run API tests
        run: dart test test/api_test.dart
      - name: Stop docker compose
        run: docker compose down
